version: "3.7"

services:
  nifi:
    image: koroslak/nifi:latest
    container_name: nifi
    restart: always
    environment:
      - NIFI_HOME=/opt/nifi/nifi-current
      - NIFI_LOG_DIR=/opt/nifi/nifi-current/logs
      - NIFI_PID_DIR=/opt/nifi/nifi-current/run
      - NIFI_BASE_DIR=/opt/nifi
      - NIFI_WEB_HTTP_PORT=8080
    ports:
      - 8080:8080
    depends_on:
      - openldap
    volumes:
      - nifi:/opt/nifi/nifi-current/state
      - nifi:/opt/nifi/nifi-current/repositories/database_repository
      - nifi:/opt/nifi/nifi-current/repositories/flowfile_repository
      - nifi:/opt/nifi/nifi-current/repositories/content_repository
      - nifi:/opt/nifi/nifi-current/repositories/provenance_repository

  postgres:
    image: koroslak/postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret123
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8090:80

  metabase:
    container_name: metabase
    image: metabase/metabase:v0.34.2
    restart: always
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase_admin
      MB_DB_PASS: secret123
      MB_DB_HOST: postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres

  openldap:
    image: osixia/openldap:1.3.0
    container_name: openldap
    restart: always
    ports:
      - 38999:389

# Mocked source systems      
  jira-api:
    image: danielgtaylor/apisprout:latest
    container_name: jira-api
    restart: always
    ports:
      - 8000:8000
    command: https://raw.githubusercontent.com/mvrabel/nifi-postgres-metabase/master/api_examples/jira-api.json

  pipedrive-api:
    image: danielgtaylor/apisprout:latest
    container_name: pipedrive-api
    restart: always
    ports:
      - 8100:8000
    command: https://raw.githubusercontent.com/mvrabel/nifi-postgres-metabase/master/api_examples/pipedrive-api.yaml
    
  restcountries-api:
    image: danielgtaylor/apisprout:latest
    container_name: restcountries-api
    restart: always
    ports:
      - 8200:8000
    command: https://raw.githubusercontent.com/mvrabel/nifi-postgres-metabase/master/api_examples/restcountries-api.json

volumes:
  postgres:
  nifi:
  openldap:
  metabase:
  pgadmin:
